# Generated by Django 4.2.17 on 2024-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FIC", "Fiction"),
                            ("SFI", "Science Fiction"),
                            ("SCI", "Science"),
                            ("BIO", "Biography"),
                            ("HIS", "History"),
                            ("ART", "Art"),
                            ("PSY", "Psychology"),
                            ("PHI", "Philosophy"),
                            ("ROM", "Romance"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("publication_year", models.DateField()),
                ("pages", models.IntegerField(max_length=5)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ENG", "English"),
                            ("GUJ", "Gujarati"),
                            ("HIN", "Hindi"),
                            ("SAN", "Sanskrit"),
                            ("URD", "Urdu"),
                            ("FRE", "French"),
                            ("GER", "German"),
                            ("SPA", "Spanish"),
                            ("RUS", "Russian"),
                        ],
                        max_length=3,
                    ),
                ),
                ("description", models.TextField()),
                ("publisher", models.CharField(max_length=225)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
