# Generated by Django 4.2.17 on 2024-12-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(related_name="books", to="books.genre"),
        ),
    ]
