# Generated by Django 4.2.17 on 2024-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_language_book_thumbnail_alter_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENG", "English"),
                    ("GUJ", "Gujarati"),
                    ("HIN", "Hindi"),
                    ("SAN", "Sanskrit"),
                    ("URD", "Urdu"),
                    ("FRE", "French"),
                    ("GER", "German"),
                    ("SPA", "Spanish"),
                    ("RUS", "Russian"),
                ],
                max_length=3,
            ),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
