# Generated by Django 4.2.17 on 2025-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_language_delete_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="subtitle",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENG", "English"),
                    ("GUJ", "Gujarati"),
                    ("HIN", "Hindi"),
                    ("SAN", "Sanskrit"),
                    ("URD", "Urdu"),
                    ("FRE", "French"),
                    ("GER", "German"),
                    ("SPA", "Spanish"),
                    ("RUS", "Russian"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
