# Generated by Django 4.2.17 on 2024-12-25 08:36

import django.core.validators
from django.db import migrations, models
import sqlalchemy.sql.sqltypes


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                default=sqlalchemy.sql.sqltypes.NullType,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
